name: E-Health Tergooi
favicon: null
layout_spectrum: 0.84737
typography_spectrum: 0.7168863550759852
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#2e393f'
    - '#6f8998'
    - '#d7d0d8'
    - '#120c0c'
    - '#b69d99'
  brandStrength: 0.4373610920738429
  lightness: 0.571064920630306
  saturation: 1
  rhythmicContrast: 0.930943547282368
purpose: []
