name: E-Health Tergooi
favicon: null
layout_spectrum: 0.7783042415976524
typography_spectrum: 0.7168863550759852
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.4373610920738429
  lightness: 0.571064920630306
  saturation: 1
  rhythmicContrast: 0.930943547282368
purpose: []
